### ISSUE TITLE
no config 

### ISSUE THREAD

**Issue by MaximalMax07** [AirplanegoBrr/BlockBreaker-BlockPlacer#3]

**Comment by MaximalMax07** [comment]
there is no config file / folder

**Comment by AirplanegoBrr** [comment]
what would the config be for?

**Comment by AirplanegoBrr** [comment]
mhh werid. Are you sure? There should be a config folder

**Comment by AirplanegoBrr** [comment]
Closing due to the issue being inactive, feel free to reopen the issue with more details!
