### ISSUE TITLE
There is a problem with permissions.

### ISSUE THREAD

**Issue by otofuserver** [AirplanegoBrr/BlockBreaker-BlockPlacer#4]
spigot-1.19.3
var 1.0

hello
There is a problem with permissions.
The description says "plugin name.use" but it is actually "use".
Unlike the description, it is difficult to understand.
I was OP and it was too late to notice.

**Comment by AirplanegoBrr** [comment]
Hello! Dev Branch has this issue fixed! I will start work on #5 (or try) and then publish the jar!
